type XModule = {
  _malloc: (n: number) => number;
  _free: (p: number) => void;
  _xdecompress: (dst: number, dstLenPtr: number, src: number, srcLen: number) => number;
  HEAPU8: Uint8Array;
};

let modulePromise: Promise<XModule> | null = null;

export async function getXdecompressModule(): Promise<XModule> {
  if (modulePromise) return modulePromise;
  modulePromise = (async () => {
    // The JS/WASM is generated by `npm run build:wasm` into this folder.
    const mod = await import('./wasm/xdecompress.mjs');
    const create = (mod as any).default as (opts?: any) => Promise<any>;
    const m = (await create({})) as XModule;
    return m;
  })();
  return modulePromise;
}

export async function xdecompress(comp: Uint8Array, expectedSize: number): Promise<Uint8Array> {
  const m = await getXdecompressModule();
  if (!m.HEAPU8) {
    throw new Error(
      'WASM module missing HEAPU8 view. Re-run `npm run build:wasm` and restart the dev server.'
    );
  }
  const srcPtr = m._malloc(comp.length);
  const dstPtr = m._malloc(expectedSize);
  const dstLenPtr = m._malloc(4);
  try {
    m.HEAPU8.set(comp, srcPtr);
    // write u32 expectedSize into dstLenPtr (little-endian)
    m.HEAPU8[dstLenPtr + 0] = expectedSize & 0xff;
    m.HEAPU8[dstLenPtr + 1] = (expectedSize >>> 8) & 0xff;
    m.HEAPU8[dstLenPtr + 2] = (expectedSize >>> 16) & 0xff;
    m.HEAPU8[dstLenPtr + 3] = (expectedSize >>> 24) & 0xff;

    const rc = m._xdecompress(dstPtr, dstLenPtr, srcPtr, comp.length);
    if (rc !== 0) throw new Error(`xdecompress failed (rc=${rc})`);

    const outLen =
      (m.HEAPU8[dstLenPtr + 0] |
        (m.HEAPU8[dstLenPtr + 1] << 8) |
        (m.HEAPU8[dstLenPtr + 2] << 16) |
        (m.HEAPU8[dstLenPtr + 3] << 24)) >>>
      0;

    const out = m.HEAPU8.slice(dstPtr, dstPtr + outLen);
    return out;
  } finally {
    m._free(srcPtr);
    m._free(dstPtr);
    m._free(dstLenPtr);
  }
}
